//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.20 at 03:09:31 PM ICT 
//


package com.napas.ach.testjackson.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NapasDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NapasDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}NapasDocumentHeader"/>
 *         &lt;element name="Payload" type="{}NapasDocumentPayload"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NapasDocument", propOrder = {
    "header",
    "payload"
})
public class NapasDocument {

    @XmlElement(name = "Header", required = true)
    protected NapasDocumentHeader header;
    @XmlElement(name = "Payload", required = true)
    protected NapasDocumentPayload payload;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link NapasDocumentHeader }
     *     
     */
    public NapasDocumentHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link NapasDocumentHeader }
     *     
     */
    public void setHeader(NapasDocumentHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link NapasDocumentPayload }
     *     
     */
    public NapasDocumentPayload getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link NapasDocumentPayload }
     *     
     */
    public void setPayload(NapasDocumentPayload value) {
        this.payload = value;
    }

}
